//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSService.Validation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AvailabilityMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AvailabilityMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSService.Validation.AvailabilityMessages", typeof(AvailabilityMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.DayOfWeek.Empty.
        /// </summary>
        public static string EmptyDayOfWeek {
            get {
                return ResourceManager.GetString("EmptyDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.EndDate.Empty.
        /// </summary>
        public static string EmptyEndDate {
            get {
                return ResourceManager.GetString("EmptyEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvailabilityException.HostId.Empty.
        /// </summary>
        public static string EmptyHostId {
            get {
                return ResourceManager.GetString("EmptyHostId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.Occurrence.Empty.
        /// </summary>
        public static string EmptyOccurrence {
            get {
                return ResourceManager.GetString("EmptyOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.RoomId.Empty.
        /// </summary>
        public static string EmptyRoomId {
            get {
                return ResourceManager.GetString("EmptyRoomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.StartDate.Empty.
        /// </summary>
        public static string EmptyStartDate {
            get {
                return ResourceManager.GetString("EmptyStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.RoomId.Inactive.
        /// </summary>
        public static string InactiveRoom {
            get {
                return ResourceManager.GetString("InactiveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.DayOfWeek.IncorrectValue.
        /// </summary>
        public static string IncorrectDayOfWeek {
            get {
                return ResourceManager.GetString("IncorrectDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.EndDate.IncorrectTime.
        /// </summary>
        public static string IncorrectEndTime {
            get {
                return ResourceManager.GetString("IncorrectEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.Occurrence.IncorrectValue.
        /// </summary>
        public static string IncorrectOccurrence {
            get {
                return ResourceManager.GetString("IncorrectOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.StartDate.IncorrectTime.
        /// </summary>
        public static string IncorrectStartTime {
            get {
                return ResourceManager.GetString("IncorrectStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.Status.IncorrectValue.
        /// </summary>
        public static string IncorrectStatus {
            get {
                return ResourceManager.GetString("IncorrectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.StartDate.EndDate.InvalidTime.
        /// </summary>
        public static string InvalidTime {
            get {
                return ResourceManager.GetString("InvalidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvailabilityException.StartDate.EndDate.TimeSpanLimit.
        /// </summary>
        public static string InvalidTimeSpan {
            get {
                return ResourceManager.GetString("InvalidTimeSpan", resourceCulture);
            }
        }
    }
}
