//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSService.Validation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RoomMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public RoomMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSService.Validation.RoomMessages", typeof(RoomMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Room.Location.IsEmpty.
        /// </summary>
        public static string EmptyRoomLocation {
            get {
                return ResourceManager.GetString("EmptyRoomLocation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Room.Name.IsEmpty.
        /// </summary>
        public static string EmptyRoomName {
            get {
                return ResourceManager.GetString("EmptyRoomName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Room.Location.TooLong.
        /// </summary>
        public static string LocationNameLong {
            get {
                return ResourceManager.GetString("LocationNameLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Room.Name.TooLong.
        /// </summary>
        public static string RoomNameLong {
            get {
                return ResourceManager.GetString("RoomNameLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Room.SameNameAndLocation.
        /// </summary>
        public static string UniqueRoom {
            get {
                return ResourceManager.GetString("UniqueRoom", resourceCulture);
            }
        }
    }
}
